services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=123@Mudar"
      - "MSSQL_PID=Developer"
    ports:
      - 1433:1433
